### ISSUE TITLE
[BUG] lamadava python api hashtag_medias_top_chunk_v1 problem

### ISSUE THREAD

**Issue by GoodWeather0322** [Lamadava/lamadava-python#5]
Hello, today I am using lamadava's hashtag_medias_top_chunk_v1 API. I expected it to continuously provide me with different max_id values so that I can keep cursoring through the data. However, it keeps giving me the same max_id repeatedly.

**Comment by i-Niki** [comment]
> Hello, today I am using lamadava's hashtag_medias_top_chunk_v1 API. I expected it to continuously provide me with different max_id values so that I can keep cursoring through the data. However, it keeps giving me the same max_id repeatedly.

Hey there!
Yep, we will fix it soon, I will write down here as soon as we end

**Comment by GoodWeather0322** [comment]
Hi, thank you for your prompt response!

**Comment by i-Niki** [comment]
> Hi, thank you for your prompt response!

Thank you for reaching us out, problem is fixed.
